import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-100">
      <Head>
        <title>AI Poster Studio - Professional E-commerce Design in Minutes</title>
        <meta name="description" content="Turn your product photos into professional marketing visuals in minutes" />
      </Head>

      {/* Navigation */}
      <nav className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16 items-center">
            <div className="flex items-center">
              <span className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
                🎨 AI Poster Studio
              </span>
            </div>
            <div className="flex space-x-4">
              <Link href="/login" className="text-gray-700 hover:text-purple-600 px-3 py-2">
                Login
              </Link>
              <Link href="/signup" className="bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700">
                Sign Up
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="text-center">
          <h1 className="text-5xl font-bold text-gray-900 mb-6">
            Turn your product photos into
            <span className="block bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
              professional marketing visuals
            </span>
          </h1>
          <p className="text-xl text-gray-600 mb-8">
            With editable text you can actually modify ✨
          </p>

          {/* Upload CTA */}
          <div className="bg-white rounded-2xl shadow-xl p-8 max-w-2xl mx-auto mb-12">
            <div className="border-2 border-dashed border-purple-300 rounded-xl p-12 hover:border-purple-500 transition-colors cursor-pointer">
              <div className="text-6xl mb-4">📸</div>
              <p className="text-lg text-gray-700 font-medium">
                Drag & drop or click to upload
              </p>
              <p className="text-sm text-gray-500 mt-2">
                Supports JPG, PNG, WEBP (Max 10MB)
              </p>
            </div>
          </div>

          {/* Features */}
          <div className="grid md:grid-cols-3 gap-8 mb-16">
            <div className="bg-white rounded-xl p-6 shadow-lg">
              <div className="text-4xl mb-4">🤖</div>
              <h3 className="text-xl font-semibold mb-2">AI Background Generation</h3>
              <p className="text-gray-600">
                Professional studio-quality backgrounds generated by AI
              </p>
            </div>
            <div className="bg-white rounded-xl p-6 shadow-lg">
              <div className="text-4xl mb-4">✏️</div>
              <h3 className="text-xl font-semibold mb-2">Editable Text</h3>
              <p className="text-gray-600">
                Unlike Midjourney, you can modify text after generation!
              </p>
            </div>
            <div className="bg-white rounded-xl p-6 shadow-lg">
              <div className="text-4xl mb-4">🎨</div>
              <h3 className="text-xl font-semibold mb-2">10+ Fonts & Colors</h3>
              <p className="text-gray-600">
                Customize your text with various styles and colors
              </p>
            </div>
          </div>

          {/* Social Proof */}
          <div className="bg-white rounded-xl p-8 max-w-3xl mx-auto mb-16 shadow-lg">
            <div className="text-3xl mb-4">⭐⭐⭐⭐⭐</div>
            <p className="text-xl text-gray-700 italic mb-4">
              "Saved me hours of Photoshop work. The editable text feature is a game-changer!"
            </p>
            <p className="text-gray-600">— Amazon Seller</p>
          </div>

          {/* Before/After Demo */}
          <div className="grid md:grid-cols-3 gap-6 mb-16">
            <div className="bg-white rounded-xl p-4 shadow-lg">
              <div className="text-center text-sm text-gray-500 mb-2">Before (Product)</div>
              <div className="bg-gray-100 rounded-lg h-48 flex items-center justify-center">
                <span className="text-4xl">📦</span>
              </div>
            </div>
            <div className="bg-white rounded-xl p-4 shadow-lg">
              <div className="text-center text-sm text-gray-500 mb-2">After (AI Generated)</div>
              <div className="bg-gradient-to-br from-purple-100 to-blue-100 rounded-lg h-48 flex items-center justify-center">
                <span className="text-4xl">✨</span>
              </div>
            </div>
            <div className="bg-white rounded-xl p-4 shadow-lg">
              <div className="text-center text-sm text-gray-500 mb-2">After (Text Edited)</div>
              <div className="bg-gradient-to-br from-blue-100 to-purple-100 rounded-lg h-48 flex items-center justify-center">
                <span className="text-4xl">🎯</span>
              </div>
            </div>
          </div>

          {/* Pricing */}
          <div className="mb-16">
            <h2 className="text-3xl font-bold mb-8">Simple Pricing</h2>
            <div className="grid md:grid-cols-2 gap-8 max-w-3xl mx-auto">
              <div className="bg-white rounded-xl p-8 shadow-lg border-2 border-gray-200">
                <h3 className="text-2xl font-bold mb-2">Free</h3>
                <p className="text-4xl font-bold mb-6">$0</p>
                <ul className="space-y-3 text-gray-600 mb-8">
                  <li>✓ 5 generations</li>
                  <li>✓ With watermark</li>
                  <li>✓ Standard quality</li>
                </ul>
                <Link href="/signup" className="block text-center bg-gray-100 text-gray-700 py-3 rounded-lg hover:bg-gray-200">
                  Get Started
                </Link>
              </div>
              <div className="bg-gradient-to-br from-purple-600 to-blue-600 rounded-xl p-8 shadow-lg text-white">
                <h3 className="text-2xl font-bold mb-2">Pro</h3>
                <p className="text-4xl font-bold mb-6">$9.9<span className="text-lg">/mo</span></p>
                <ul className="space-y-3 mb-8">
                  <li>✓ 50 generations/month</li>
                  <li>✓ HD quality, no watermark</li>
                  <li>✓ Editable text</li>
                  <li>✓ Priority support</li>
                </ul>
                <Link href="/signup" className="block text-center bg-white text-purple-600 py-3 rounded-lg hover:bg-gray-100 font-semibold">
                  Start Free Trial
                </Link>
              </div>
            </div>
          </div>

          {/* CTA Buttons */}
          <div className="flex justify-center space-x-6">
            <Link href="/editor" className="bg-purple-600 text-white px-8 py-4 rounded-xl text-lg font-semibold hover:bg-purple-700 shadow-lg">
              Get Started
            </Link>
            <Link href="#pricing" className="bg-white text-purple-600 px-8 py-4 rounded-xl text-lg font-semibold hover:bg-gray-50 shadow-lg border-2 border-purple-600">
              View Pricing
            </Link>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-white border-t mt-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="text-center text-gray-600">
            <p>© 2026 AI Poster Studio. Built with ❤️ by Linda</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
